### ISSUE TITLE
Automatically uninstall packages

### ISSUE THREAD

**Issue by camchenry** [es-tooling/module-replacements-codemods#12]
This might be a bit of a stretch beyond just editing the JS code, but it would be neat if the CLI for this eventually uninstalled the actual packages themselves. That is, if you have the `is-regexp` package installed (for example) it would also remove it from:

- `package.json`
- `package-lock.json`
- whatever other lock/package files you have

The end goal being that the CLI will completely purge your project of these modules wherever they might be referenced.

**Comment by ajkl2533** [comment]
I think this could work only for direct dependencies mentioned in `package.json` file because codemods will clean your own codebase but you have no control over third party dependencies.
This actually might be task for the CLI (once there will be any) that could perform uninstall after all selected codemods are done. It seems more safe option than touch `package.lock` or lockfiles directly.

**Comment by thepassle** [comment]
Yep, agree. Theres a todo in the code somewhere that mentions this. The cli is super barebones right now, its just there to have something, im mainly focused on gathering/implementing the codemods right now. @43081j had some ideas around the cli as well

**Comment by thepassle** [comment]
I wonder if it would be enough to glob for `**/package.json`, and just remove the packages from the hits there, since the codemods will already glob for all js/ts/etc files anyway, and that way it would work for monorepos too
